# 
# for postprod


vars:
  hosts: 
    iml-20XX-XXX: # <-- UPDATE HERE!
      year: "20XX"
      no_notif: "XXX"
      fixture_filename: XXXXXX_mysql.sql

      web_port: "{{ ((( year|int)-2000)|int|abs) }}{{ no_notif}}"
      db_port: "{{ ((( year|int)-2000)|int|abs) }}{{ 1000-(no_notif|int|abs) }}"
      git_sha: XXXXXX


local:
  hosts:
    iml-20XX-XXX: # <-- UPDATE HERE!

andes_monolithic:
  hosts:
    iml-20XX-XXX: # <-- UPDATE HERE!
